name: wtf

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

  
jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      actions: write
      
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        
 #     - name: Get current date
#        id: date
#        run: |
#          echo "action_time=$(date +'%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"
          
#      - name: Output current path
#        run: |
#          echo "Current path: $(pwd)"
#          mkdir -p config
#          echo "Hello, world!" > config/wc.yml
          
      - name: Commit and push
        run: |
          git config --local user.email "test+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          # git pull --rebase
          git checkout --orphan latest_branch
          git rm -rf --cached .
          # 指定目录
          directory="./.github/workflows/"
          # 当前日期
          current_date=$(date +'%Y-%m-%d')
          # 查找指定目录下的所有文件
          find "$directory" -type f | while read -r file; do
              # 获取文件名
              file_name=$(basename "$file")
              # 替换文件名中的日期为当前日期
              new_file_name="${file_name//????-??-??/$current_date}"
              # 如果新文件名与旧文件名相同，则跳过
              if [[ $new_file_name == $file_name ]]; then
                  continue
              fi
              # 重命名文件
              mv "$file" "$(dirname "$file")/$new_file_name"
          done
          git add -A
          git commit -m "$(date +'%Y-%m-%d %H:%M:%S') OK"
          git branch -D main
          git branch -m main
          git push -f origin main
